{% set name = "perl-io-socket-ssl" %}
{% set version = "2.083" %}
{% set sha256 = "904ef28765440a97d8a9a0df597f8c3d7f3cb0a053d1b082c10bed03bc802069" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/S/SU/SULLR/IO-Socket-SSL-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0
  script:
    - perl Makefile.PL INSTALLDIRS=vendor NO_PERLLOCAL=1 NO_PACKLIST=1
    - make
    - make test
    - make install VERBINST=1

requirements:
  build:
    - make
  host:
    - perl
    - perl-extutils-makemaker
    - perl-net-ssleay
  run:
    - perl
    - perl-net-ssleay

test:
  imports:
    - IO::Socket::SSL

about:
  home: https://metacpan.org/dist/IO-Socket-SSL
  license: GPL-1.0-or-later OR Artistic-1.0-Perl
  license_family: OTHER
  summary: 'Nearly transparent SSL encapsulation for IO::Socket::INET.'
  license_file:
    - {{ environ["PREFIX"] }}/man/man1/perlartistic.1
    - {{ environ["PREFIX"] }}/man/man1/perlgpl.1

extra:
  recipe-maintainers:
    - cbrueffer
